var fs = require('fs');
var util = require('util');
var exec = util.promisify(require('child_process').exec);

var MAJOR_REVISION = '1';
var MINOR_REVISION = '0';

exec('git rev-list HEAD', (err, stdout) => {
    var buildNumber = stdout.toString().split(/\r\n|\r|\n/).length;
    exec('git rev-parse --abbrev-ref HEAD', (err, stdout) => {
        var branch = stdout.toString().trim();
        console.log(`AppVersion: ${MAJOR_REVISION}.${MINOR_REVISION}.${buildNumber} - Branch: '${branch}'`);

        const content = `
// this file is automatically generated by git.version.ts script
export const AppBuildInfo = {
  branch: '${branch}',
  majorVersion: ${MAJOR_REVISION},
  minorVersion: ${MINOR_REVISION},
  buildNumber: ${buildNumber},
  versionString: ${MAJOR_REVISION}.${MINOR_REVISION}.${buildNumber},
  timeStamp: ${Date.now()}
};
`;

        fs.writeFileSync('src/environments/versions.ts', content, {encoding: 'utf8'});
    });
});
